### ISSUE TITLE
Script downloads a max of 1000 images from the Aura Frame website

### ISSUE THREAD

**Issue by doc10101** [meub/aura-frame-downloader#1]
This script is fantastic and works as suggested (as long as one has installed the key dependency, which is "requests"). However, the script can only download 1000 images and then terminates (but not with an error). It would be helpful to look into this behavior to determine if the script could be edited to download an unlimited number of pictures from a given user's Aura account.

**Comment by meub** [comment]
The script has been updated to support more than 1000 images now. I just tested and it worked with 1037 images. Let me know if it works for you!

**Comment by doc10101** [comment]
Yes! just downloaded 3,478 pictures successfully. Great job on this very useful script!
