### ISSUE TITLE
Aura Uploading + Client

### ISSUE THREAD

**Issue by zmanowar** [meub/aura-frame-downloader#2]
Hello!

This inspired me! I spent some time over the past week looking into more of the Aura Frames API and ended up writing a client that tries to implement more functionality: https://github.com/zmanowar/auraupload

Lots of TODOs (and ugly patterns to fix) left but thought I'd shoot you a link in case you were curious!

Cheers

**Comment by meub** [comment]
Nice, this is cool! I'll check it out. Glad you were inspired :)
