### ISSUE TITLE
Different pictures with same item["taken_at"] are not downloaded

### ISSUE THREAD

**Issue by prrk47002** [meub/aura-frame-downloader#3]
If more than one picture on the frame has the same item["taken_at"] time, the second (and any subsequent) pictures with that timestamp are skipped, even if they are different pictures.  In my case, the result was 10 photos skipped.

The reason this happens is the code that checks if new_filename exists and does a "continue" if it does so so as to not download it a second time.

      # check if file exists and skip it if so
      if os.path.isfile(file_path + new_filename):
        print(counter, "Skipping!", new_filename, "already downloaded" )
        counter = counter + 1
        continue
        
   
Since each photo on the frame is named with a unique UUID, I'd suggest the following change so new_filename is unique for every picture and skipping already downloaded pictures will still work as expected.

    new_filename = item["taken_at"] + "_" + item["file_name"]

This also eliminates need for the multiple  if/elif block to append an extension on the new_filename

      if  item["file_name"].endswith(".jpeg"):
        new_filename = new_filename + ".jpeg"
      ...
      

I'll put a pull request  in sometime this week for your review

**Comment by meub** [comment]
Thank you for this fix :)
