### ISSUE TITLE
Any way to get past the first 1000 pictures?

### ISSUE THREAD

**Issue by johnson29630** [meub/aura-frame-downloader#7]
Ran across this script and have successfully run it against our frame. Would like to get at all our photos, wondering if there is any way? Our frame was a gift from our kids, and they all keep adding grandkid pictures that I would like to retrieve.

I tried adding an 'offset' parameter, but no affect.
frame_url = "https://api.pushd.com/v5/frames/" + frame_id + "/assets.json?limit=1000&offset=1000&side_load_users=false"

Are there any any other parameters for the api, or any other way to get past the 1000 image limit?

**Comment by johnson29630** [comment]
Located updated versions, now pulls all images.

**Comment by meub** [comment]
Nice! Mind making a PR?
